"""create communication tables

Revision ID: bd20292fcd86
Revises: 
Create Date: 2025-11-26 17:43:56.434319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd20292fcd86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('nickname', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('profile_image_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('refresh_token', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['profile_image_id'], ['images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('communication',
    sa.Column('c_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'STOPPED', 'FAILED', name='communicationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('c_id')
    )
    op.create_index('idx_created_at', 'communication', ['created_at'], unique=False)
    op.create_index('idx_user_id', 'communication', ['user_id'], unique=False)
    op.create_table('c_voice_files',
    sa.Column('c_vf_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_format', sa.String(length=10), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['c_id'], ['communication.c_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('c_vf_id')
    )
    op.create_index('idx_c_id', 'c_voice_files', ['c_id'], unique=False)
    op.create_index(op.f('ix_c_voice_files_c_id'), 'c_voice_files', ['c_id'], unique=False)
    op.create_table('c_stt_results',
    sa.Column('c_sr_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('c_vf_id', sa.Integer(), nullable=False),
    sa.Column('stt_type', sa.Enum('CHIRP', 'LONG', name='stttype'), nullable=False),
    sa.Column('json_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['c_id'], ['communication.c_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['c_vf_id'], ['c_voice_files.c_vf_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('c_sr_id'),
    sa.UniqueConstraint('c_id', 'stt_type', name='uq_c_id_stt_type')
    )
    op.create_index('idx_c_id_stt_type', 'c_stt_results', ['c_id', 'stt_type'], unique=False)
    op.create_index('idx_c_vf_id', 'c_stt_results', ['c_vf_id'], unique=False)
    op.create_index(op.f('ix_c_stt_results_c_id'), 'c_stt_results', ['c_id'], unique=False)
    op.create_index(op.f('ix_c_stt_results_c_vf_id'), 'c_stt_results', ['c_vf_id'], unique=False)
    op.create_table('c_bert_results',
    sa.Column('c_br_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('c_sr_id', sa.Integer(), nullable=False),
    sa.Column('target_speaker', sa.String(length=20), nullable=False),
    sa.Column('curse_count', sa.Integer(), nullable=False),
    sa.Column('filler_count', sa.Integer(), nullable=False),
    sa.Column('standard_score', sa.Float(), nullable=True),
    sa.Column('analyzed_segments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['c_id'], ['communication.c_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['c_sr_id'], ['c_stt_results.c_sr_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('c_br_id'),
    sa.UniqueConstraint('c_id')
    )
    op.create_table('c_results',
    sa.Column('c_result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('c_br_id', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('speech_rate', sa.Float(), nullable=False),
    sa.Column('silence', sa.Float(), nullable=False),
    sa.Column('clarity', sa.Float(), nullable=False),
    sa.Column('meaning_clarity', sa.Float(), nullable=False),
    sa.Column('cut', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('advice', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['c_br_id'], ['c_bert_results.c_br_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['c_id'], ['communication.c_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('c_result_id'),
    sa.UniqueConstraint('c_br_id'),
    sa.UniqueConstraint('c_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('c_results')
    op.drop_table('c_bert_results')
    op.drop_index(op.f('ix_c_stt_results_c_vf_id'), table_name='c_stt_results')
    op.drop_index(op.f('ix_c_stt_results_c_id'), table_name='c_stt_results')
    op.drop_index('idx_c_vf_id', table_name='c_stt_results')
    op.drop_index('idx_c_id_stt_type', table_name='c_stt_results')
    op.drop_table('c_stt_results')
    op.drop_index(op.f('ix_c_voice_files_c_id'), table_name='c_voice_files')
    op.drop_index('idx_c_id', table_name='c_voice_files')
    op.drop_table('c_voice_files')
    op.drop_index('idx_user_id', table_name='communication')
    op.drop_index('idx_created_at', table_name='communication')
    op.drop_table('communication')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index('idx_email', table_name='users')
    op.drop_table('users')
    op.drop_table('images')
    # ### end Alembic commands ###
